# Generated by Django 3.0.8 on 2020-08-12 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstore', '0002_auto_20200807_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=16)),
                ('memail', models.CharField(max_length=32)),
                ('mphone', models.CharField(max_length=10)),
                ('mmsg', models.TextField()),
            ],
        ),
    ]
