# Generated by Django 3.0.8 on 2020-08-13 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rstore', '0003_msg'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='cust',
        ),
    ]
