# Generated by Django 3.0.8 on 2020-08-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rstore', '0004_auto_20200814_0527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cust',
            old_name='usradd1',
            new_name='custadd1',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usradd2',
            new_name='custadd2',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usrcity',
            new_name='custcity',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usrdist',
            new_name='custdist',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usremail',
            new_name='custemail',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usrfname',
            new_name='custfname',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usrlname',
            new_name='custlname',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usrphn',
            new_name='custphn',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usrpincode',
            new_name='custpincode',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usrpwd',
            new_name='custpwd',
        ),
        migrations.RenameField(
            model_name='cust',
            old_name='usrstate',
            new_name='custstate',
        ),
    ]
