# Generated by Django 3.0.8 on 2020-11-26 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstore', '0005_auto_20200814_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='clin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=16)),
                ('cimg', models.ImageField(upload_to='assets/images/clientimg')),
            ],
        ),
    ]
