# Generated by Django 3.0.8 on 2020-11-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstore', '0006_clin'),
    ]

    operations = [
        migrations.AddField(
            model_name='clin',
            name='cliishigh',
            field=models.BooleanField(default=False),
        ),
    ]
