# Generated by Django 3.0.8 on 2020-12-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstore', '0007_clin_cliishigh'),
    ]

    operations = [
        migrations.AddField(
            model_name='clin',
            name='clinurl',
            field=models.CharField(default='#', max_length=64),
        ),
    ]
