# Generated by Django 4.0.1 on 2022-01-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstore', '0008_clin_clinurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clin',
            name='clinurl',
            field=models.CharField(max_length=64),
        ),
    ]
