# Generated by Django 4.0.1 on 2022-01-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv', models.IntegerField(default=0)),
                ('servname', models.CharField(max_length=16)),
                ('servcost', models.IntegerField(default=0)),
                ('servqnt', models.IntegerField(default=0)),
                ('servtotal', models.IntegerField(default=0)),
                ('cust', models.IntegerField(default=0)),
                ('custname', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='clin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=16)),
                ('cimg', models.ImageField(upload_to='assets/images/clientimg')),
                ('cliishigh', models.BooleanField(default=False)),
                ('clinurl', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='cust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custfname', models.CharField(max_length=16)),
                ('custlname', models.CharField(max_length=16)),
                ('custemail', models.CharField(max_length=32)),
                ('custphn', models.CharField(max_length=12)),
                ('custpwd', models.CharField(max_length=16)),
                ('custadd1', models.CharField(max_length=64)),
                ('custadd2', models.CharField(max_length=64)),
                ('custcity', models.CharField(max_length=16)),
                ('custdist', models.CharField(max_length=16)),
                ('custstate', models.CharField(max_length=16)),
                ('custpincode', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=16)),
                ('memail', models.CharField(max_length=32)),
                ('mphone', models.CharField(max_length=10)),
                ('mmsg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='serv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servname', models.CharField(max_length=16)),
                ('servdesc', models.TextField()),
                ('servcost', models.IntegerField(default=0)),
                ('servpic', models.ImageField(upload_to='assets/images/productimg')),
                ('servishigh', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serv', models.IntegerField(default=0)),
                ('servname', models.CharField(max_length=16)),
                ('servcost', models.IntegerField(default=0)),
                ('servqnt', models.IntegerField(default=0)),
                ('cust', models.IntegerField(default=0)),
                ('custname', models.CharField(max_length=16)),
            ],
        ),
    ]
