# Generated by Django 4.0.1 on 2022-01-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='memail',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='msg',
            name='mname',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='msg',
            name='mphone',
            field=models.CharField(max_length=128),
        ),
    ]
